# Generated by Django 2.2 on 2019-04-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Roles')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Users')),
            ],
        ),
        migrations.CreateModel(
            name='RoleModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Modules')),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Roles')),
            ],
        ),
    ]
