# Generated by Django 2.2 on 2019-04-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190425_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
