# Generated by Django 2.2 on 2019-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
