# Generated by Django 2.2 on 2019-04-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('pub_come', models.CharField(max_length=50, verbose_name='出版社')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='出版日期')),
            ],
            options={
                'verbose_name': '图书表',
                'verbose_name_plural': '图书表',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('college', models.CharField(max_length=20, verbose_name='学院名')),
                ('num', models.CharField(max_length=20, verbose_name='学号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借书日期')),
                ('return_date', models.DateTimeField(verbose_name='归还日期')),
                ('status', models.CharField(default='否', max_length=20, verbose_name='是否归还')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '借阅表',
                'verbose_name_plural': '借阅表',
            },
        ),
    ]
