# Generated by Django 2.2 on 2019-04-19 08:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('qmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
