# Generated by Django 2.2 on 2019-04-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190419_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qpub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
