# Generated by Django 2.2 on 2019-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190419_1710'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='qpub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
